{{- if .Values.gcsSync.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.gcsSync.pvc.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany  # must be rwx
  resources:
    requests:
      storage: {{ .Values.gcsSync.pvc.request }}
  storageClassName: ""  # must be ""
  volumeName: {{ .Values.gcsSync.pvc.volumeName }}
{{- end }}